### ISSUE TITLE
Exception unhandled when parsing response to JSON

### ISSUE THREAD

**Issue by felimartina** [DanWebb/uphold-sdk-node#5]
I was trying this sdk out and multiple times came across an unhandled exception on the **responseHandler** funciton.
For some reason uphold sometimes returns and HTML response instead of a JSON response then the code fails to parse it. I tried to read the HTML but it doesn't say anything really important (I was excepting something from uphold like: hey we are busy now try later).
I'd suggest to wrap line 23 in a try/catch statement and handle the exception as an error.

This is what the returned HTML looks like, if it is of any help.
`
<!DOCTYPE html><html lang="en-US">  <head>    <meta charset="utf-8" />    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />    <title>Uphold</title>    <meta name="description" content="Join the world's fastest growing platform for moving, converting, transacting and holding any form of money or commodity. Instantly, securely and for free." />    <meta name="keywords" content="Money service, Bitcoin wallet, Bitcoin payments, Payment processor, Money transfer, peer-to-peer payments, b2b payments, payments, bitcoin, bitcoin volatility, digital currency, cryptocurrency" />    <meta name="author" content="Uphold" />    <meta name="language" content="en-US" />    <meta name="robots" content="noindex, nofollow" />    <meta property="og:title" content="Uphold" />    <meta property="og:description" content="Join the world's fastest growing platform for moving, converting, transacting and holding any form of money or commodity. Instantly, securely and for free." />    <meta property="og:site_name" content="Uphold" />    <meta property="og:url" content="https://uphold.com/" />    <meta property="og:latitude" content="37.7919757" />    <meta property="og:longitude" content="-122.4004308" />    <meta property="og:street-address" content="301 Battery St" />    <meta property="og:locality" content="San Francisco" />    <meta property="og:region" content="CA" />    <meta property="og:postal-code" content="94111" />    <meta property="og:country-name" content="United States" />    <meta property="og:type" content="website" />        <meta name="theme-color" content="#4aaf57" />    <meta name="mobile-web-app-capable" content="yes" />        <meta name="apple-mobile-web-app-capable" content="yes" />        <meta name="msapplication-navbutton-color" content="#4aaf57" />    <meta name="msapplication-TileColor" content="#4aaf57" />    <meta name="msapplication-TileImage" content="favicon-144.png" />                                <style>.container::after,.container::before{content:" ";display:table}.container::after{clear:both}a{background-color:transparent;color:#6bc176;text-decoration:none;transition:all .15s linear}a:active,a:hover{outline:0}b,strong{font-weight:700}h1{font-size:2.2em}*,::after,::before{box-sizing:border-box}html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-size:16px;-webkit-tap-highlight-color:transparent;position:relative;min-height:100%}.sr-only,footer{position:absolute}@media(max-width:991px){html{font-size:14px}}@media(max-width:767px){html{font-size:13px}}body{min-width:20rem;font-family:proxima-nova,"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:.9375rem;line-height:1.25;color:#454b5c;background-color:#f6f6f7;margin:0 0 2.5rem}footer{left:0;right:0;bottom:15px}a:focus,a:hover{color:#429d4e;text-decoration:underline;outline:0}small{font-size:.75rem}p{margin:0 0 .625rem}h1,h2,h3,h4,h5,h6{font-family:inherit;font-weight:600;line-height:1.5;color:#454b5c;margin:2.5rem 0 1.25rem}.container{margin-right:auto;margin-left:auto;padding-left:.9375rem;padding-right:.9375rem}@media(min-width:768px){.container{width:46.875rem}}@media(min-width:992px){.container{width:60.625rem}}@media(min-width:1200px){.container{width:73.125rem}}.sr-only{width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 ,0 ,0 ,0);border:0}.text-center{text-align:center}.text-muted{color:#8A9297}</style>    <script>//<![CDATA[window.Typekit||(window.Typekit={}),window.Typekit.config={a:"2123542",c:[".tk-proxima-nova",'"proxima-nova",sans-serif'],f:"//use.typekit.net/c/51c23f/1w;proxima-nova,2,cdh:T:i4,cdX:T:i7,cdb:T:n1,cdg:T:n4,g8x:T:n7/{format}{/extras*}?3bb2a6e53c9684ffdc9a98f31c5b2a62f1c741504d00d3f6062e51a3be427c044257270b9ab63fbb1976e8c79d60466feea5843e76cf6edcc7f17ce996434f24db447466d887d201d65c5f6f4b1a4a1af967246df987adf2cc7bbada62612c65647f2338caa65c6484ededf49b0b212f0a01038f4480bdd3d7abe65bc94cce70abe6b59de565697b3970128e24022e04d885a5d18daae707604b6b60ac8e85878699091c470554435e07d9e501fe7ad3f840ba3d09cfe4ae4e84f3769bc685ec72a596d8509e6e4578ea243feb3e8a3c24bb16400add5f04d90d6266bedeecbd82969aa85fe0d11263a926f41d14bccddc7edc9f6c9ce89a33ae10a988b14e94",fi:[139,140,171,175,176],fn:["proxima-nova",["i4","i7","n1","n4","n7"]],ht:"tk",js:"1.14.0",k:"//use.typekit.net/{id}.js",kt:"pmx7upg",l:"typekit",p:"//p.typekit.net/p.gif?s=1&k=pmx7upg&ht=tk&h={host}&f=139.140.171.175.176&a=2123542&_={_}",ps:1,w:"pmx7upg"},function(t,n,e){function i(t,n,e){return t.call.apply(t.bind,arguments)}function o(t,n,e){if(!t)throw Error();if(2<arguments.length){var i=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);return Array.prototype.unshift.apply(e,i),t.apply(n,e)}}return function(){return t.apply(n,arguments)}}function r(t,n,e){return r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?i:o,r.apply(null,arguments)}function a(t,n){this.qa=t,this.X=n||t,this.B=this.X.document}function s(t,e,i){t=t.B.getElementsByTagName(e)[0],t||(t=n.documentElement),t.insertBefore(i,t.lastChild)}function h(t,n){function e(){t.B.body?n():setTimeout(e,0)}e()}function u(t,n,e){n=n||[],e=e||[];for(var i=t.className.split(/\s+/),o=0;o<n.length;o+=1){for(var r=!1,a=0;a<i.length;a+=1)if(n[o]===i[a]){r=!0;break}r||i.push(n[o])}for(n=[],o=0;o<i.length;o+=1){for(r=!1,a=0;a<e.length;a+=1)if(i[o]===e[a]){r=!0;break}r||n.push(i[o])}t.className=n.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function f(t,n){for(var e=t.className.split(/\s+/),i=0,o=e.length;o>i;i++)if(e[i]==n)return!0;return!1}function c(t){if("string"==typeof t.Ha)return t.Ha;var n=t.X.location.protocol;return"about:"==n&&(n=t.qa.location.protocol),"https:"==n?"https:":"http:"}function l(t){return t.X.location.hostname||t.qa.location.hostname}function p(t,n,e,i){function o(t){for(var e=0;e<a.length;e++)if(a[e].href&&-1!==a[e].href.indexOf(n))return void t();setTimeout(function(){o(t)},0)}var r=t.createElement("link",{rel:"stylesheet",href:n,media:i?"only x":"all"}),a=t.B.styleSheets,h=!1;r.onload=function(){h||(h=!0,e&&e(null))},r.onerror=function(){h||(h=!0,e&&e(Error("Stylesheet failed to load")))},s(t,"head",r),i&&o(function(){r.media="all"})}function d(t,n,e){var i=t.B.getElementsByTagName("head")[0];if(i){var o=t.createElement("script",{src:n}),r=!1;o.onload=o.onreadystatechange=function(){r||this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(r=!0,e&&e(null),o.onload=o.onreadystatechange=null,"HEAD"==o.parentNode.tagName&&i.removeChild(o))},i.appendChild(o),setTimeout(function(){r||(r=!0,e&&e(Error("Script load timeout")))},5e3)}}function g(t){this.Fa=t||"-"}function w(t,n){this.e=t,this.u=t.X.document.documentElement,this.$=n,this.p="wf",this.o=new g("-"),this.Aa=!1!==n.events,this.J=!1!==n.classes}function m(t){if(t.J){var n=f(t.u,t.o.h(t.p,"active")),e=[],i=[t.o.h(t.p,"loading")];n||e.push(t.o.h(t.p,"inactive")),u(t.u,e,i)}v(t,"inactive")}function v(t,n,e){t.Aa&&t.$[n]&&(e?t.$[n](e.getName(),y(e)):t.$[n]())}function b(t,n){this.Y=t,this.ga=4,this.Z="n";var e=(n||"n4").match(/^([nio])([1-9])$/i);e&&(this.Z=e[1],this.ga=parseInt(e[2],10))}function y(t){return t.Z+t.ga}function k(t,n){this.e=t,this.G=n,this.r=this.e.createElement("span",{"aria-hidden":"true"},this.G)}function S(t){s(t.e,"body",t.r)}function x(t){var n;n=[];for(var e=t.Y.split(/,\s*/),i=0;i<e.length;i++){var o=e[i].replace(/['"]/g,"");-1==o.indexOf(" ")?n.push(o):n.push("'"+o+"'")}return n=n.join(","),e="normal","o"===t.Z?e="oblique":"i"===t.Z&&(e="italic"),"display:block;position:absolute;top:-9999px;left:-9999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+n+";"+("font-style:"+e+";font-weight:"+(t.ga+"00")+";")}function O(t,n,e,i,o,r,a){this.ha=t,this.Ea=n,this.e=e,this.A=i,this.G=a||"BESbswy",this.I={},this.fa=o||3e3,this.ra=r||null,this.R=this.Q=this.P=this.O=null,this.O=new k(this.e,this.G),this.P=new k(this.e,this.G),this.Q=new k(this.e,this.G),this.R=new k(this.e,this.G),t=new b(this.A.getName()+",serif",y(this.A)),t=x(t),this.O.r.style.cssText=t,t=new b(this.A.getName()+",sans-serif",y(this.A)),t=x(t),this.P.r.style.cssText=t,t=new b("serif",y(this.A)),t=x(t),this.Q.r.style.cssText=t,t=new b("sans-serif",y(this.A)),t=x(t),this.R.r.style.cssText=t,S(this.O),S(this.P),S(this.Q),S(this.R)}function N(){if(null===Bt){var n=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(t.navigator.userAgent);Bt=!!n&&(536>parseInt(n[1],10)||536===parseInt(n[1],10)&&11>=parseInt(n[2],10))}return Bt}function T(t,n,e){for(var i in Ct)if(Ct.hasOwnProperty(i)&&n===t.I[Ct[i]]&&e===t.I[Ct[i]])return!0;return!1}function P(t){var n,e=t.O.r.offsetWidth,i=t.P.r.offsetWidth;(n=e===t.I.serif&&i===t.I["sans-serif"])||(n=N()&&T(t,e,i)),n?At()-t.Ka>=t.fa?N()&&T(t,e,i)&&(null===t.ra||t.ra.hasOwnProperty(t.A.getName()))?C(t,t.ha):C(t,t.Ea):A(t):C(t,t.ha)}function A(t){setTimeout(r(function(){P(this)},t),50)}function C(t,n){setTimeout(r(function(){this.O.remove(),this.P.remove(),this.Q.remove(),this.R.remove(),n(this.A)},t),0)}function B(t,n,e){this.e=t,this.F=n,this.ba=0,this.va=this.pa=!1,this.fa=e}function I(t){0==--t.ba&&t.pa&&(t.va?(t=t.F,t.J&&u(t.u,[t.o.h(t.p,"active")],[t.o.h(t.p,"loading"),t.o.h(t.p,"inactive")]),v(t,"active")):m(t.F))}function E(){this.K=this.T=-1}function M(){var t=[{name:"font-family",value:Jt.c[$t+1]}];this.Ia=[Jt.c[$t]],this.ka=t}function W(t){for(var n=t.Ia.join(","),e=[],i=0;i<t.ka.length;i++){var o=t.ka[i];e.push(o.name+":"+o.value+";")}return n+"{"+e.join("")+"}"}function K(t,n,e,i){this.n=null!=t?t:null,this.w=null!=n?n:null,this.S=null!=e?e:null,this.h=null!=i?i:null}function U(t,n){return-1===t.compare(n)}function j(t,n){return 0===t.compare(n)||1===t.compare(n)}function R(t,n){return 0===t.compare(n)||-1===t.com... (length: 43638)
`

**Comment by DanWebb** [comment]
Hey @felimartina, could you let me know which API endpoint or method you were trying to call that returned this?

**Comment by felimartina** [comment]
@DanWebb I was just using the **ticker**. This is the snippet:
`uphold.tickersForCurrency('BTCUSD', function (err, current_tick) { ... });`
I'm kinda of  Node.js newby but I think this is very straight forward. And yes, I logged in before trying to call this method.

**Comment by DanWebb** [comment]
Hi @felimartina just testing this, the only way I can get it to return html is by setting the host to something other than the api in the config object. For example:

```
var Uphold = require('./uphold')({
     host: "uphold.com"
});
```

The only two values host should contain is either `api-sandbox.uphold.com` for the sandbox environment or `api.uphold.com` for the live environment. If the host property is left blank it will default to `api.uphold.com` may just want to double check this in your app.

I've added a try catch block anyway just in case here c8ab12a.
