### ISSUE TITLE
Issue with getting PAT

### ISSUE THREAD

**Issue by amaendeepm** [DanWebb/uphold-sdk-node#8]
I am getting this error: TypeError: Uphold.createPAT is not a function while executing below code when I switched on using PAT creation for authentication :

var Uphold = require('uphold-sdk-node');

Uphold.createPAT('development@ernit.com', 'XXXX', 'ERNIT PAT desc', false, function(err, res) {

if(err) {
   console.log('Error authenticating with Uphold');
} 
// add the PAT to the current configs pat property and make authenticated calls
Uphold.addPAT(res.accessToken).user(function(err, user) {
   if(err) return customErrorHandler(err);
        console.log(user);
    });
});

What could be problem here ?

**Comment by DanWebb** [comment]
`var Uphold = require('uphold-sdk-node');` returns a function which must be called with a config object as it's parameters.

The config object is described here: https://github.com/DanWebb/uphold-sdk-node#installation essentially the first line of your code should be changed to look more like this: `var Uphold = require('uphold-sdk-node')({});`
